In [1]:
import pandas as pd
import re
import json

In [2]:
def extract_first_json(text):
    
    text = (
        text
        .replace(" ","")
        .replace("\n","")
        .replace("True", "true")
        .replace("False", "false")
        .replace("None", "null")
        .replace("'",'"')
    )
    match = re.search(r'\{.*?\}', text)
    if match:
        try:
            json_data = json.loads(match.group())
            return json_data
        except json.JSONDecodeError as e:
            print(match.group())
            print("failed", e)
            return {}
    else:
        print("format failed")
        return {}

def extract_last_json(text):
    text = (
        text
        .replace(" ","")
        .replace("\n","")
        .replace("True", "true")
        .replace("False", "false")
        .replace("None", "null")
        .replace("'",'"')
    )
    # Find all JSON objects in the text
    matches = list(re.finditer(r'\{.*?\}', text))
    if matches:
        # Get the last match
        last_match = matches[-1]
        try:
            json_data = json.loads(last_match.group())
            return json_data
        except json.JSONDecodeError as e:
            print(last_match.group())
            print("failed", e)
            return {}
    else:
        print("format failed")
        return {}

In [42]:
# pred_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/final_preds_LLM_pfub_and_invoice_25-03-2026_prompt_v2.csv")
#pred_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/OCR_LLM_PREDS_pfub_and_invoice_25-03-2026_prompt_v2.csv")

pred_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/ocr_raw_data_plus_prod_2025-01-20_to_2025-02-27_PREDS_01_04_2026_PROMPT_V4.csv")

In [4]:
pred_data

,ticket_uuid,attachment_id,text,object_key,document_type,clean_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,source,lentgh,pred_llm
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,13703,"Okay, let's tackle this classification step by..."
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,14529,"Okay, let's tackle this classification task st..."
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,16442,"Okay, let's tackle this document classificatio..."
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,13878,"Okay, let's tackle this classification step by..."
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,13635,"Okay, let's tackle this classification step by..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10757,eae76ab8-0752-5c44-8726-5f920f8e6f0a,51170436,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...,NaN,fp_invoice,gerichtsvollzieher\nsiemensstraße 20\nsteinsie...,NaN,False,False,NaN,080d5f6c1c195c1abfcf9107e6bcf70367e6bd8c521df1...,s3://pair-data-engineering-new/ocr_prepared_ou...,prod,7924,"Alright, let's tackle this classification task..."
10758,c6723ec9-b3bd-53f3-a7ba-121f8e6d708a,52618215,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...,NaN,bailiff_ip,wildeshauser str. 21\nsandra zenker\n26197 ahl...,NaN,False,False,NaN,dcbb82c7982aa1a6f43b73f48cf71e520983dfeaf361f4...,s3://pair-data-engineering-new/ocr_prepared_ou...,prod,1500,"Okay, let's tackle this classification step by..."
10759,d66ee21e-705e-5729-9a82-d5821667f99d,50758910,André Rucks\nSittarder Str. 72\n52511 Geilenki...,NaN,tbd,andré rucks\nsittarder str. 72\n52511 geilenki...,NaN,False,False,NaN,e60667129a00c38ab5c8e70001a2ebbd49c13e9eb6e0f3...,s3://pair-data-engineering-new/ocr_prepared_ou...,prod,2182,"Okay, let's tackle this document classificatio..."
10760,33751aae-53eb-5874-910a-65d80b66e082,51118089,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,NaN,fp_invoice,sonnenscheinpfad 28\n44879 bochum\ntel. 0234/4...,NaN,False,False,NaN,01a1a0d3674e331b26566e92f62e666c0a295ef7eca672...,s3://pair-data-engineering-new/ocr_prepared_ou...,prod,2089,"Okay, let's tackle this classification task st..."
10761,353f4e7f-5046-522f-a69b-b6965f7a60b5,50427647,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...,NaN,fp_invoice,obergerichtsvollzieher\n34226 fuldatal\nwürz\n...,NaN,False,False,NaN,709cd8bf8f5a1f979b83897c6a4a2ca933a8bfbd47a5d9...,s3://pair-data-engineering-new/ocr_prepared_ou...,prod,9874,"Okay, let's tackle this document classificatio..."

In [5]:
#pred_data.source.value_counts()

In [6]:
pred_data.pred_llm.isna().sum()

np.int64(0)

In [7]:
pred_data.created_at.min()

AttributeError: 'DataFrame' object has no attribute 'created_at'

In [8]:
pred_data.is_pfub.value_counts()

is_pfub
False    9820
True      942
Name: count, dtype: int64

In [43]:
pred_data["pred_json"] = pred_data["pred_llm"].apply(extract_first_json)

In [44]:
pred_data = pred_data[pred_data["pred_json"] != {}].copy()

In [45]:
# extract is_erlass and is_invoice from pred_json
pred_data["llm_is_pfub"] = pred_data["pred_json"].apply(lambda x: x.get("is_pfub", None))
pred_data["llm_is_invoice"] = pred_data["pred_json"].apply(lambda x: x.get("is_invoice_inside", None))

In [12]:
pred_data.isna().sum()

ticket_uuid             0
attachment_id           0
text                    0
object_key           2686
document_type           0
clean_text              0
data                 9832
is_pfub                 0
is_ladung               0
s3_link             10338
textract_job_id         0
textract_s3_link        0
source                  0
lentgh                  0
pred_llm                0
pred_json               0
llm_is_pfub             0
llm_is_invoice          0
dtype: int64

In [46]:
pred_data_ocr = pred_data[pred_data["source"] == "ocr"]
pred_data_prod = pred_data[pred_data["source"] == "prod"]

In [14]:
wrong_predictions = pred_data_ocr[pred_data_ocr["is_pfub"] != pred_data_ocr["llm_is_pfub"]]
wrong_predictions

,ticket_uuid,attachment_id,text,object_key,document_type,clean_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,source,lentgh,pred_llm,pred_json,llm_is_pfub,llm_is_invoice
6,41c5ecfd-2b9d-5364-81b8-db9d86577ea5,16dd90f1-4ed1-5dd1-98d5-1408bc44b052,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,01.04.2025/ocr-v2_54_M_1067_25_Schreiben_vom_3...,approved_attachment_and_transfer_order,amtsgericht memmingen\nabteilung für zwangsvol...,"{'case_slug': '163464253141', 'debtor_name': '...",True,False,NaN,d3220801ad866b43be8d71cebdd044cd9cbedae7ff5be4...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1675,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
10,737e68b1-d955-5abd-89a8-3c9bcfd89ebd,350b91d6-2dfd-5be6-bd1d-58a4c9eacf02,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,01.06.2022/1654077659_Doc_01062022_000000001_1...,approved_seizure,amtsgericht frankfurt am main\nmobiliarzwangsv...,"{'case_slug': '110872558124', 'debtor_name': '...",True,False,NaN,39f6bde0d7784c8fa3429f3108940f87d90d22c690f63f...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,2159,"Okay, let's tackle this classification step by...","{'is_pfub': False, 'is_invoice_inside': True}",False,True
13,2116361b-c0e3-55bf-8f20-5f40d00525ce,7df7ef68-9412-5f70-bd3d-9a6d761f7223,Amtsgericht Münster\n-33- Amtsgericht Münster ...,01.07.2024/ocr-v2_BB_005_01072024_122825.pdf,approved_seizure,amtsgericht münster\n-33- amtsgericht münster ...,"{'case_slug': '136916228754', 'debtor_name': '...",True,False,NaN,8b9ea31725e645286d54e60bab67292043350aaf8f2814...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1287,"Okay, let me tackle this classification step b...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
27,3b4dad76-4092-584c-af03-8454f5749e6f,3b07ae04-4e33-5cb3-bd04-6b4b7239ea33,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,01.08.2023/1690879027_KD_004_01082023_100925.pdf,approved_seizure,amtsgericht frankfurt am main\nmobiliarzwangsv...,"{'case_slug': '124540063102', 'debtor_name': '...",True,False,NaN,c00bc269cdcb9bcc5d17b071d6a510af0a244f277ff1e1...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1740,"Okay, let's tackle this classification step by...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
28,ca1bdfd7-9b8d-5707-a353-d3910c8794ae,f6926285-9b57-5491-9989-407b37033ec4,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,01.08.2023/1690879031_KD_005_01082023_100925.pdf,approved_seizure,amtsgericht frankfurt am main\nmobiliarzwangsv...,"{'case_slug': None, 'debtor_name': 'Backhit, S...",True,False,NaN,91a96bbff37a498b9b915722b920ba86f02c2f7156dc8b...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1734,"Alright, let's tackle this classification task...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3814,b811bfb4-241b-5d50-8456-154dc9cf34fc,20b6c6bc-1023-5977-889a-a30d2a8a016f,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,30.01.2024/ocr-v2_JD_003_30012024_095337.pdf,approved_seizure,amtsgericht frankfurt am main\nmobiliarzwangsv...,"{'case_slug': '110875750652', 'debtor_name': '...",True,False,NaN,809169037d8f0fbdb134974fda6632fc47eadff7b56ba0...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1668,"Okay, let's tackle this classification step by...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
3815,f4cf0f8c-5da0-5218-ae4c-026afb7a7860,00bb8b3e-90f4-5c30-a304-a17124ae30e4,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,30.01.2024/ocr-v2_JD_003_30012024_095348.pdf,approved_seizure,amtsgericht frankfurt am main\nmobiliarzwangsv...,"{'case_slug': '111542555227', 'debtor_name': '...",True,False,NaN,809169037d8f0fbdb134974fda6632fc47eadff7b56ba0...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,2082,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': True}",False,True
3913,f0161ced-1f2b-5113-ad99-997d99e8dfbd,ae965f31-3da7-56cb-b391-23d68f11bc93,Amtsgericht Münster\n-33- Amtsgericht Münster ...,30.06.2023/1688119527_DS_001_30062023_115829.pdf,approved_seizure,amtsgericht münster\n-33- amtsgericht münster ...,"{'case_slug': '120444962613', 'debtor_name': N...",True,False,NaN,7c58a52845b52f9afe4881731f17a8b58bd0525cad9540...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1348,"Okay, let's tackle this classification step by...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
3939,92385e88-1264-54ba-97b2-3a71221526c4,8b4b44c7-6fa8-5ff4-9d25-0eba6cc2e846,Amtsgericht Münster\n-33- Amtsgericht Münster ...,30.10.2025/ocr-v2_c0872fd7aa1c431e.pdf,approved_attachment_and_transfer_order,amtsgericht münster\n-33- amtsgericht münster ...,"{'case_slug': '181060314323', 'debtor_name': '...",True,False,NaN,2e2ace9d7d5a381975ca3541f0a81a3e8d161f2c6686c1...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1081,"Alright, let's tackle this classification task...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
3999,31d2513b-9ad1-53fc-a31f-c91f7e846ff2,26f76c76-fc0d-5109-9f45-427fc1a24bc9,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,31.07.2023/1690794316_KD_004_31072023_110320.pdf,approved_seizure,amtsgericht frankfurt am main\nmobiliarzwangsv...,"{'case_slug': '125677855012', 'debtor_name': '...",True,False,NaN,db30fc9d20ccd495194936c243c753fe06765697d4e620...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1760,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': False}",False,False

In [15]:
print(wrong_predictions.document_type.value_counts())

document_type
approved_seizure                          91
approved_attachment_and_transfer_order    31
Name: count, dtype: int64

In [16]:
false_positives = wrong_predictions[(wrong_predictions["is_pfub"] == False) & (wrong_predictions["llm_is_pfub"] == True)]
false_positives.document_type.value_counts()

Series([], Name: count, dtype: int64)

In [17]:
false_positives.shape

(0, 18)

In [18]:
false_negatives = wrong_predictions[(wrong_predictions["is_pfub"] == True) & (wrong_predictions["llm_is_pfub"] == False)]
print(false_negatives.document_type.value_counts())

document_type
approved_seizure                          91
approved_attachment_and_transfer_order    31
Name: count, dtype: int64

In [19]:
false_negatives.shape

(122, 18)

#### precision, recall and f1 on OCR pred data

In [28]:
# consiredering is_pfub as the correct label, calculate precision, recall and f1 score for llm_is_pfub
from sklearn.metrics import precision_score, recall_score, f1_score
# remove document type attachment_and_transfer_order from the data and then calculate the scores
precision = precision_score(pred_data_ocr["is_pfub"], pred_data_ocr["llm_is_pfub"], pos_label=True)
recall = recall_score(pred_data_ocr["is_pfub"], pred_data_ocr["llm_is_pfub"], pos_label=True)
f1 = f1_score(pred_data_ocr["is_pfub"], pred_data_ocr["llm_is_pfub"], pos_label=True)
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Precision: 1.0
Recall: 0.7409766454352441
F1 Score: 0.8512195121951219

## OCR dataset: some random examples from False Positives

In [ ]:
false_positives

#### For ocr dataset files, read the data from pair-scanner/['object_key']. It is directly under pair-scanner

In [ ]:
import sys
import os
sys.path.append("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation")

from utils.prod_utils import download_pdf_by_document_s3_info
import boto3

session = boto3.Session(profile_name="739275445236_DataScienceUser")
s3 = session.client("s3")
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fps"

In [24]:
def download_files_in_sample(sample_df, download_dir):
    os.makedirs(download_dir, exist_ok=True)
    idx = 0
    for _, row in sample_df.iterrows():
        
        print(f"Downloading file for attachment_id: {row['attachment_id']}, idx: {idx}")
        download_pdf_by_document_s3_info(
            s3=s3,
            document_s3_bucket=row["document_s3_bucket"],
            document_s3_key=row["document_s3_key"],
            download_dir=download_dir,
            file_name=row.get("file_name", None)
        )
        idx += 1 
        
def download_files_in_sample_OCR_dataset(sample_df, download_dir):
    os.makedirs(download_dir, exist_ok=True)
    idx = 0
    for _, row in sample_df.iterrows():
        
        print(f"Downloading file for attachment_id: {row['attachment_id']}, idx: {idx}")
        download_pdf_by_document_s3_info(
            s3=s3,
            document_s3_bucket="pair-scanner",
            document_s3_key=row["object_key"],
            download_dir=download_dir,
            file_name=row.get("file_name", None)
        )
        idx += 1

In [ ]:
# sample = false_positives.sample(n=100, random_state=42)
sample = false_positives.copy() # take all
download_files_in_sample_OCR_dataset(sample, download_dir)

In [ ]:
sample

In [ ]:
# SAVE WRONG ATTTACHMENT IDS TO REVIEW IN STREAMLIT APP LATER
WRONG_ATTACHMENT_IDS = sample["attachment_id"].tolist()
WRONG_ATTACHMENT_IDS

In [ ]:
# take not takes sample of false positives to review the files in streamlit app
sample_2 = false_positives[~false_positives["attachment_id"].isin(WRONG_ATTACHMENT_IDS)]
sample_2

In [ ]:
WRONG_ATTACHMENT_IDS_REST = sample_2["attachment_id"].tolist()
WRONG_ATTACHMENT_IDS_REST

In [ ]:
download_files_in_sample_OCR_dataset(sample_2, download_dir)

## OCR dataset: some random examples from False Negative

In [21]:
import sys
import os
sys.path.append("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation")

from utils.prod_utils import download_pdf_by_document_s3_info
import boto3

session = boto3.Session(profile_name="739275445236_DataScienceUser")
s3 = session.client("s3")
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns"

In [25]:
sample = false_negatives.sample(n=60, random_state=42)
download_files_in_sample_OCR_dataset(sample, download_dir)

Downloading file for attachment_id: 179e07e6-24cf-5b50-a6e2-51b93d36f127, idx: 0
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1696236517_KD_001_02102023_103939.pdf
Downloading file for attachment_id: 53a3e6f3-176a-5166-901b-ae47ec70c081, idx: 1
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1646825443_Doc_09032022_000000003_122527_1.pdf
Downloading file for attachment_id: 39c837e8-6531-5ed0-926b-73de9c8bcf70, idx: 2
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1646839834_Doc_09032022_000000001_161230_1.pdf
Downloading file for attachment_id: c4a7b7ba-6dca-5c1b-bf74-99af3e6a74a3, idx: 3
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_53_M_3604_25_Anschreiben_AG_Memmingen.pdf
Downloading file for attachment_id: f6926285-9b57-5491-9989-407b37033ec4, idx: 4
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1690879031_KD_005_01082023_100925.pdf
Downloading file for attachment_id: f8a0420c-ee55-5621-8799-dd1dc08f789f, idx: 5
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1683552911_DS_003_08052023_151142.pdf
Downloading file for attachment_id: c29bb55c-f94a-5bd8-b541-dc13a21f4b1a, idx: 6
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1684150548_DS_003_15052023_131354.pdf
Downloading file for attachment_id: 62b5c4d1-ca08-5fd8-86a8-e53ee957c824, idx: 7
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1701164098_KD_002_28112023_102722.pdf
Downloading file for attachment_id: 95ee141b-05ac-586b-8d5a-05e09ce1dc94, idx: 8
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1649259040_Doc_06042022_000000001_171442_1.pdf
Downloading file for attachment_id: 79534ff5-324a-5d92-80af-235d2a1af8d8, idx: 9
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1689237307_KD_001_13072023_100719.pdf
Downloading file for attachment_id: 3fb732e9-60b2-51b1-8ed6-a517dec8d618, idx: 10
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_9b286913-0ebd-44ef-ac69-002d4b136596.pdf
Downloading file for attachment_id: ae965f31-3da7-56cb-b391-23d68f11bc93, idx: 11
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1688119527_DS_001_30062023_115829.pdf
Downloading file for attachment_id: b5885663-7ad4-57ca-9581-6aac48e18831, idx: 12
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1685703975_DS_001_02062023_125038.pdf
Downloading file for attachment_id: e4000d63-ac11-5c82-96e9-682c592a9272, idx: 13
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_b3001e8b1bf6455d.pdf
Downloading file for attachment_id: ef5f68dd-5ba1-5e63-8359-8be8d2931141, idx: 14
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1695985515_KD_002_29092023_123439.pdf
Downloading file for attachment_id: 0cdb669f-a06d-5350-8cb5-02ff3dbd8a07, idx: 15
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1685703982_DS_003_02062023_125038.pdf
Downloading file for attachment_id: 89658438-26e4-51b0-8542-66cae89cbfd5, idx: 16
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1666170048_Scan_YA_00619102022_105856.pdf
Downloading file for attachment_id: e84511e2-6ab9-53c3-93c8-1f723ef8cb22, idx: 17
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1663066865_Scan_HV_006_13092022_125413.pdf
Downloading file for attachment_id: e366018e-ec74-5810-bd49-158556e4e5d6, idx: 18
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_JD_002_30012024_095337.pdf
Downloading file for attachment_id: 16dd90f1-4ed1-5dd1-98d5-1408bc44b052, idx: 19
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_54_M_1067_25_Schreiben_vom_31_03_2025_formlos_AG_Memmingen.pdf
Downloading file for attachment_id: 016cf422-68bd-5703-99e9-0aaa07fa2eaa, idx: 20
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_54_M_1479_25_Schreiben_vom_02_05_2025_formlos_AG_Memmingen.pdf
Downloading file for attachment_id: 1ddcc555-2745-5ff3-adc6-992cf0957306, idx: 21
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1662631248_Scan_HV_003_08092022_113131.pdf
Downloading file for attachment_id: 9c4757d5-92c3-50bb-bc90-2a339cca44b8, idx: 22
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1639663247_Doc_16122021_000000003_145356_1.pdf
Downloading file for attachment_id: 3affdf5c-5879-58d2-9f4b-f9917b8279f0, idx: 23
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_53_M_3226_24_Schreiben_vom_26_11_2024_formlos_AG_Memmingen.pdf
Downloading file for attachment_id: ead02b14-6edf-5a61-801c-623258726730, idx: 24
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_b655aab1cf7f435d.pdf
Downloading file for attachment_id: 80fa72f3-8f6e-59bd-bcb1-25ef1970568d, idx: 25
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_53_M_2720_25_Schreiben_vom_07_08_2025_formlos_AG_Memmingen.pdf
Downloading file for attachment_id: 48f05d95-3d01-58d0-8e75-5705dd288baa, idx: 26
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_RB_001_28072025_091413.pdf
Downloading file for attachment_id: c24b1e55-5083-5fb1-94e8-9d40d07a83fa, idx: 27
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_48855bacff7f4a8c.pdf
Downloading file for attachment_id: b332ce31-b655-51c5-b388-af66125fe8dc, idx: 28
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_f71328a2-7a9f-4fe4-85bb-b34a4d420de3.pdf
Downloading file for attachment_id: f2053a98-1bcd-5601-8754-416a514b2a33, idx: 29
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1651156234_Doc_28042022_000000001_160854_1.pdf
Downloading file for attachment_id: 20eb45f2-2d5c-5a4a-ae5f-0a8c87839bf0, idx: 30
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1685703986_DS_004_02062023_125038.pdf
Downloading file for attachment_id: 6454046a-690c-5cb1-846f-3e7f71fa1194, idx: 31
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1690970707_PF_005_02082023_114807.pdf
Downloading file for attachment_id: 2da1d7cf-e7a1-56c6-a175-06910b23b3de, idx: 32
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_KL_005-18112024-135516.pdf
Downloading file for attachment_id: b39b5ded-b587-513f-a5db-c7469ba0c1a9, idx: 33
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_4ddb453253bb45c4.pdf
Downloading file for attachment_id: 6f440b96-441b-5918-a913-945e82a0b79c, idx: 34
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_JD_003_30012024_095333.pdf
Downloading file for attachment_id: 287e2054-4eb3-5ba4-9549-bd1266608b71, idx: 35
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_KD_001_25012024_090321.pdf
Downloading file for attachment_id: 2d4ceff0-a3c0-5c65-a6e8-93d92441bfc6, idx: 36
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_RB_001_22042025_085238.pdf
Downloading file for attachment_id: ccc53f70-5c3b-5624-a82f-c9985461966b, idx: 37
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1688548024_KD_009_05072023_110057.pdf
Downloading file for attachment_id: b639c174-53b7-5b2a-a65d-72ccb7e61da7, idx: 38
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_54_M_3722_24_Schreiben_vom_18_11_2024_formlos_AG_Memmingen.pdf
Downloading file for attachment_id: 4bdaad9c-82e2-501d-b3ca-64fbd0708b63, idx: 39
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_FA_004_16042025_090213.pdf
Downloading file for attachment_id: 6be1c2bb-de5d-58d7-a140-77c140174e32, idx: 40
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_KL_006-02042025-145002.pdf
Downloading file for attachment_id: cd972024-1e21-59de-95b9-c200b05fe571, idx: 41
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1686045928_DS_007_06062023_120451.pdf
Downloading file for attachment_id: bdb23e49-aff5-5239-89c0-c855b11e5040, idx: 42
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_RB_008_04122024_133334.pdf
Downloading file for attachment_id: 3c00347a-bf90-55f1-8d55-efbff839b9a8, idx: 43
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1658142066_Doc_18072022_000000001_123514_1.pdf
Downloading file for attachment_id: 7dbc9c8e-d2dd-550a-be53-e97fbff51e1e, idx: 44
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1688548014_KD_002_05072023_110058.pdf
Downloading file for attachment_id: 8b4b44c7-6fa8-5ff4-9d25-0eba6cc2e846, idx: 45
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_c0872fd7aa1c431e.pdf
Downloading file for attachment_id: 3fc71228-6cc3-547e-8b93-653e51126ca0, idx: 46
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1672326299_Scan_TB_002_29122022_155545.pdf
Downloading file for attachment_id: ae1f84d9-bef4-58ba-803e-3b9f3f082960, idx: 47
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_KL_006-01082025-080649.pdf
Downloading file for attachment_id: beed3022-cb48-55c4-9fbb-674a78e51ad8, idx: 48
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_KD_002_16012024_100036.pdf
Downloading file for attachment_id: 1fcd1463-f230-5e2e-b55e-1a06a23810a9, idx: 49
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_FA_005_18022025_112225.pdf
Downloading file for attachment_id: 346435d3-26b6-575b-821c-b83e031a5a2f, idx: 50
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1686126894_PF_006_07062023_100943.pdf
Downloading file for attachment_id: c77bda6f-ecf5-5cbc-8863-05ccd8485b06, idx: 51
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1641825031_Doc_10012022_000000001_151725_1.pdf
Downloading file for attachment_id: 94bd1e00-b10e-5bf9-94e0-59836cf3165b, idx: 52
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1670321138_Scan_YA_00201122022_152605.pdf
Downloading file for attachment_id: 6e142967-56b2-5c7e-b90f-d93d1280582d, idx: 53
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1662107446_Scan_AK_003_02092022_101103.pdf
Downloading file for attachment_id: c3083b5a-050a-54e5-8735-5d9e74f699d5, idx: 54
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1652779835_Doc_17052022_000000004_111900_1.pdf
Downloading file for attachment_id: 1da86098-d719-5531-8f51-40aae2a88144, idx: 55
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_53_M_2439_24_Schreiben_vom_05_09_2024_formlos_AG_Memmingen.pdf
Downloading file for attachment_id: fc7072ca-55cd-5895-a151-17c3bbfd92e3, idx: 56
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/1684753602_DS_003_22052023_125746.pdf
Downloading file for attachment_id: 75c31cc8-d8ae-58e6-aae1-0ce5acfa373f, idx: 57
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_KD_002_02022024_092223.pdf
Downloading file for attachment_id: 36faf893-167a-5675-831b-c25a2d21c5cd, idx: 58
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_RB_001-08082025-080718.pdf
Downloading file for attachment_id: 42a121ea-c5f5-5a61-a01a-e2b5b659ec72, idx: 59
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/fns/ocr-v2_54_M_4109_24_Schreiben_vom_18_12_2024_formlos_AG_Memmingen.pdf

### OCR: Check pfub=True invoice=True

In [47]:
pred_data_ocr.columns

Index(['ticket_uuid', 'attachment_id', 'text', 'object_key', 'document_type',
       'clean_text', 'data', 'is_pfub', 'is_ladung', 's3_link',
       'textract_job_id', 'textract_s3_link', 'source', 'lentgh', 'pred_llm',
       'pred_json', 'llm_is_pfub', 'llm_is_invoice'],
      dtype='object')

In [51]:
pred_data_ocr.shape

(5381, 18)

In [52]:
pred_data_prod.shape

(5381, 18)

In [49]:
check = pred_data_ocr[(pred_data_ocr['llm_is_pfub']) & (pred_data_ocr['llm_is_invoice'])]
check

,ticket_uuid,attachment_id,text,object_key,document_type,clean_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,source,lentgh,pred_llm,pred_json,llm_is_pfub,llm_is_invoice
250,e17f07dd-1c5b-5fd2-b375-464674b9f396,1676c7f2-34bb-5b96-bb2c-c31d0cabc4ff,"Amtsgericht Meldorf\nAmtsgericht Meldorf, PF 8...",03.11.2022/1667471723_Scan_YA_00503112022_1129...,approved_seizure,"amtsgericht meldorf\namtsgericht meldorf, pf 8...","{'case_slug': '107570636574', 'debtor_name': N...",True,False,NaN,45bcedfae65fb65e6f53cdbcfd8bc7be5edbfe9f29248f...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,2098,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
310,26ea90de-a9a3-5ddc-b877-0d190be00ccd,737f53c3-06cb-55fe-b11c-29c04805eb79,PAIR Finance GmbH\n03. Mai 2023\nAZ\nAmtsgeric...,04.05.2023/1683194720_DS_003_04052023_113834.pdf,approved_seizure,pair finance gmbh\n03. mai 2023\namtsgericht f...,"{'case_slug': '116777659586', 'debtor_name': N...",True,False,NaN,634e9a8849d74af79cf8d5c9f198712a787ed7f41d3917...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1590,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1572,de26e15a-8ad3-579a-bc67-228afd06dfbd,897b16c1-dbd9-566c-a997-f58d23d2f59d,Amtsgericht Duisburg\n-634- Amtsgericht Duisbu...,13.07.2023/1689237319_KD_002_13072023_100721.pdf,approved_attachment_and_transfer_order,amtsgericht duisburg\n-634- amtsgericht duisbu...,NaN,True,False,NaN,7a97389ae36b0962c0213219b49c6ecda7b55c1cf7d90b...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1978,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
2999,4f32b390-20e1-513c-8c5f-6339fdb10a03,9f5ec1aa-41f2-5507-b845-34560c34d9a4,Amtsgericht Oberhausen\n-114- Amtsgericht Ober...,23.08.2023/1692795912_PF_004_23082023_145248.pdf,approved_seizure,amtsgericht oberhausen\n-114- amtsgericht ober...,"{'case_slug': '111094381204', 'debtor_name': '...",True,False,NaN,730288c883a02afa8b5f7ed3f0f2146f074ca20d5966a1...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,1466,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
3872,a1f0c884-cfac-51ef-b0e5-82cc9aa09e0f,86701733-1022-5d9d-ae4e-f911a01bd9ab,PAIR Finance GmbH\n30. März 2022\nAmtsgericht ...,30.03.2022/1648647042_Doc_30032022_000000003_1...,approved_seizure,pair finance gmbh\n30. märz 2022\namtsgericht ...,"{'case_slug': '111348836029', 'debtor_name': N...",True,False,NaN,a0cc7e6bca458734f56c8b7f89506bda69cc75e552ae94...,s3://pair-data-engineering-new/ocr_prepared_ou...,ocr,2085,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True

In [50]:
# downlado check
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/check"
download_files_in_sample_OCR_dataset(check, download_dir)

Downloading file for attachment_id: 1676c7f2-34bb-5b96-bb2c-c31d0cabc4ff, idx: 0
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/check/1667471723_Scan_YA_00503112022_112945.pdf
Downloading file for attachment_id: 737f53c3-06cb-55fe-b11c-29c04805eb79, idx: 1
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/check/1683194720_DS_003_04052023_113834.pdf
Downloading file for attachment_id: 897b16c1-dbd9-566c-a997-f58d23d2f59d, idx: 2
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/check/1689237319_KD_002_13072023_100721.pdf
Downloading file for attachment_id: 9f5ec1aa-41f2-5507-b845-34560c34d9a4, idx: 3
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/check/1692795912_PF_004_23082023_145248.pdf
Downloading file for attachment_id: 86701733-1022-5d9d-ae4e-f911a01bd9ab, idx: 4
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/ocr/check/1648647042_Doc_30032022_000000003_152944_1.pdf

In [ ]:
# # fix
# a_ids_to_fix = [
#     "258e4657-76ba-5b66-85e4-a5488359447d",
#     "77138425-4531-5c39-96ac-56b14de15d95",
#     "df5ca100-0d3b-5df2-b23e-cdb464b5ebc4",
#     "c638c53a-80ec-5aa7-ac60-88a51a1766d7",
#     "897b16c1-dbd9-566c-a997-f58d23d2f59d"
# ]

# # 1) fix pred data
# pred = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/OCR_LLM_PREDS_pfub_and_invoice_25-03-2026_prompt_v2.csv")
# pred.loc[pred["attachment_id"].isin(a_ids_to_fix), "is_pfub"] = True

# # 2) fix raw data

# raw = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")
# raw.loc[raw["attachment_id"].isin(a_ids_to_fix), "is_pfub"] = True


# # save with same name to overwrite
# pred.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/OCR_LLM_PREDS_pfub_and_invoice_25-03-2026_prompt_v2.csv", index=False)
# raw.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv", index=False)

# CHECKS FOR PROD DATA PREDICTIONS

## 1) Check 10 Examples Where llm said pfub and no invoice

In [ ]:
tp_no_invoice = pred_data[(pred_data.llm_is_pfub==True) & (pred_data.llm_is_invoice==False)]
sample = tp_no_invoice.sample(60, random_state=42)
download_files_in_sample(sample, "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/pfub_no_invoice_llm_pred")

## 2) Check 10 Examples Where llm said not pfub and no invoice

In [ ]:
tp_no_invoice = pred_data[(pred_data.llm_is_pfub==False) & (pred_data.llm_is_invoice==False)]
sample = tp_no_invoice.sample(15, random_state=10)
download_files_in_sample(sample, "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/no_pfub_no_invoice_llm_pred")

## 3) Check 10 Examples Where llm said PFUB and INVOICE

In [ ]:
tp_no_invoice = pred_data[(pred_data.llm_is_pfub==True) & (pred_data.llm_is_invoice==True)]
sample = tp_no_invoice.sample(min(20,tp_no_invoice.shape[0]), random_state=42)
download_files_in_sample(sample, "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/pfub_true_invoice_true_llm_pred")

## 4) Check 10 Examples WHERE LLM=PFUB, RF= NOT PFUB (fp)

In [ ]:
fp_against_binary_model = pred_data[(pred_data.llm_is_pfub==True) & (pred_data.is_pfub==False)]
sample = fp_against_binary_model.sample(50, random_state=4)
download_files_in_sample(sample, "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/fp_against_binary_model")

## 5) Check 10 Examples WHERE LLM=NOT PFUB, RF= PFUB (fn)

In [ ]:
fp_against_binary_model = pred_data[(pred_data.llm_is_pfub==False) & (pred_data.is_pfub==True)]
sample = fp_against_binary_model.sample(10, random_state=1)
download_files_in_sample(sample, "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/fn_against_binary_model")

### note: looks like we dont have much false negatives. llm model works better for negative cases
-> there are some hard examples that says PFUB order is NOT granted/requesting further docs etc., binary model outputs positive for some of them, llm model is better at catching this hard examples

# add invoice count algorithm

In [ ]:
import re
class InvoiceDetector():
    def __init__(self):
        self.token_count_th = 10
        self.important_tokens_for_invoice = [
            'rechnung',
            'erinnerung',
            'zahlung',
            'chemnitz',
            'landesjustizkasse',
            'betrag',
            'landeshauptkasse',
            'kassenzeichen',
            'abs',
            'kostenrechnung'
        ]
        pattern = r'\b(' + '|'.join(re.escape(token) for token in self.important_tokens_for_invoice) + r')\b'
        self.token_counting_pattern = re.compile(pattern)

    def extract(self, text: str) -> tuple[bool, int]:
        invoice_token_count = len(self.token_counting_pattern.findall(text.lower()))
        is_invoice_attached = invoice_token_count > self.token_count_th
        return is_invoice_attached, invoice_token_count

In [ ]:
detector = InvoiceDetector()

pred_data['is_invoice_attached'], pred_data['invoice_token_count'] = zip(*pred_data['clean_text'].apply(detector.extract))

In [ ]:
pred_data

In [ ]:
llm_found_invoices = pred_data[pred_data['llm_is_invoice'] == True]
llm_found_invoices.invoice_token_count.min(), llm_found_invoices.invoice_token_count.max()

In [ ]:
check = llm_found_invoices[llm_found_invoices['invoice_token_count']<5]
check

In [ ]:
download = check.sample(n=10, random_state=42)

In [ ]:
download

In [ ]:
import sys
import os
sys.path.append("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation")

from utils.prod_utils import download_pdf_by_document_s3_info
import boto3

session = boto3.Session(profile_name="739275445236_DataScienceUser")
s3 = session.client("s3")
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/pfub_with_invoice_llm_pred"

os.makedirs(download_dir, exist_ok=True)

# print invoice token counts too
for _, row in download.iterrows():
    print(f"Downloading {row['document_s3_key']} with invoice token count: {row['invoice_token_count']}")
    download_pdf_by_document_s3_info(
        s3=s3,
        document_s3_bucket=row["document_s3_bucket"],
        document_s3_key=row["document_s3_key"],
        download_dir=download_dir,
        file_name=row.get("file_name", None)
    )

In [ ]:
is_pfub = pred_data[pred_data['is_pfub']]
is_pfub

In [ ]:
is_pfub.invoice_token_count.hist()

In [ ]:
check = is_pfub[is_pfub['invoice_token_count']>=2]
check

## Check llm reasonings for wrong preds

In [ ]:
wrong_preds_attachment_ids = [54079706, 50453801, 53752403, 50426386, 53413215, 50763396, 53752407, 50426389, 50396793]

check = pred_data[pred_data['attachment_id'].isin(wrong_preds_attachment_ids)]
check

In [ ]:
download_files_in_sample(check, "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/WRONG_PREDICTIONS_CHECK_REASONING")