In [1]:
import os
import json
from ast import literal_eval
from datetime import datetime, timedelta

import pandas as pd

import numpy as np
from IPython.display import clear_output

from python_utilities.db_connection import DbConnection

In [2]:
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')

INFO [2026-02-25 12:12:22] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

In [3]:
past_ndays=1
today = datetime.now().date()
start_date = datetime.combine(today - timedelta(days=past_ndays), datetime.min.time())
end_date = datetime.combine(today, datetime.max.time())
print(f"Start Date: {start_date}")
print(f"End Date: {end_date}")
print(f"Fetching data for last {past_ndays} days")

Start Date: 2026-02-24 00:00:00
End Date: 2026-02-25 23:59:59.999999
Fetching data for last 1 days

In [4]:
data_ticket_with_attachments = analytics_db.sql_to_df(f"""
    SELECT llm_attachments.ticket_uuid as at_uuid, llm_tickets.ticket_uuid, llm_tickets.egvp_id, llm_tickets.origin, llm_tickets.status, llm_attachments.attachment_id, llm_attachments.created_at
    FROM llm_attachments
    LEFT JOIN llm_tickets ON llm_tickets.ticket_uuid = llm_attachments.ticket_uuid
""")

In [13]:
sum(data_ticket_with_attachments['at_uuid'] == data_ticket_with_attachments['ticket_uuid'])

1107775

In [14]:
data_ticket_with_attachments.ticket_uuid.isnull().sum()

np.int64(12081)

In [6]:
temp = data_ticket_with_attachments[data_ticket_with_attachments.ticket_uuid.isnull()]

In [ ]:
23718687574428-1

In [7]:
temp[temp['attachment_id'].str.contains('-')]

,at_uuid,ticket_uuid,egvp_id,origin,status,attachment_id,created_at
833978,57d149e0-3687-4f8a-8bde-13e6eea2462a,None,None,None,None,23718687574428-1,2025-11-20 16:35:09
834082,57e6360c-a5a5-4734-9cca-2a209ba01ff2,None,None,None,None,23719535154204-1,2025-11-20 16:59:07
834083,57e6360c-a5a5-4734-9cca-2a209ba01ff2,None,None,None,None,23719535154204-2,2025-11-20 16:59:07
834086,d5db383f-f265-48ab-81b8-dd9d3ae80606,None,None,None,None,23719587176092-1,2025-11-21 15:19:13
834087,d5db383f-f265-48ab-81b8-dd9d3ae80606,None,None,None,None,23719587176092-2,2025-11-21 15:19:13
...,...,...,...,...,...,...,...
1077596,4bd9badb-9ea1-456f-b3d3-7bbdc8802125,None,None,None,None,25086494501788-1,2026-01-26 16:31:22
1077597,4bd9badb-9ea1-456f-b3d3-7bbdc8802125,None,None,None,None,25086494501788-2,2026-01-26 16:31:22
1077598,4bd9badb-9ea1-456f-b3d3-7bbdc8802125,None,None,None,None,25086494501788-3,2026-01-26 16:31:22
1077599,4bd9badb-9ea1-456f-b3d3-7bbdc8802125,None,None,None,None,25086494501788-4,2026-01-26 16:31:22
1077600,4bd9badb-9ea1-456f-b3d3-7bbdc8802125,None,None,None,None,25086494501788-5,2026-01-26 16:31:22

In [8]:
null_attachments = data_ticket_with_attachments[data_ticket_with_attachments['attachment_id'].isnull()]

In [10]:
null_attachments

Empty DataFrame
Columns: [at_uuid, ticket_uuid, egvp_id, origin, status, attachment_id, created_at]
Index: []

In [ ]:
null_attachments.sort_values(by='created_at', ascending=False)

,ticket_uuid,egvp_id,origin,status,attachment_id,created_at
855,eb17bfde-0119-4332-8e26-a0bfe504dea5,NRW_B21769503765168cb31c0b0-247c-4634-962a-d76...,DE,processed,None,2026-01-27 09:44:00
842,6d18f27f-6dad-4c64-ae66-1ab0cd191285,NRW_B217695017831318853190a-737b-47ba-b9f7-6ca...,DE,processed,None,2026-01-27 09:44:00
829,046239ff-43e7-4ab7-87d9-b7fb2146fb30,NRW_B217695022856487b01ed3a-7494-4157-993f-0a6...,DE,processed,None,2026-01-27 09:44:00
830,09096444-5dbc-4a32-8b58-e995518b321f,NRW_B2176950418609915e87bf9-99cd-49c9-9425-b19...,DE,processed,None,2026-01-27 09:44:00
831,0a392392-6e2b-4eec-a467-f6d248f5729b,NRW_B2176950315577846ef5ff5-f575-44f9-bf30-baa...,DE,processed,None,2026-01-27 09:44:00
...,...,...,...,...,...,...
10,8580f6c4-cc5b-4f47-9845-76a64c921bc4,NRW_B21769150887707083eb154-16cc-453f-bf43-aa3...,DE,processed,None,2026-01-23 07:44:00
11,aee46cc4-d423-4610-8e49-81cfd8a5a5bb,NRW_B2176915171394378e65ff6-16f8-40bd-a0be-495...,DE,processed,None,2026-01-23 07:44:00
12,b6f1c518-cc1c-4ea1-ae37-efc9242645d7,NRW_B21769149664394e4ff8311-8fe1-4c52-88b0-ce9...,DE,processed,None,2026-01-23 07:44:00
13,b810cdaf-5d87-464c-9d7a-5d017fde3f8c,NRW_B21769149838422692da03d-47e8-433f-8964-ed7...,DE,processed,None,2026-01-23 07:44:00
3,0a06a476-a578-4b7b-a6c2-6ff9baa91d2d,NRW_B21769151110229d6f67c21-7789-4ba0-91bb-984...,DE,processed,None,2026-01-23 07:44:00

In [ ]:
null_attachments['origin'].value_counts()

origin
DE    2568
Name: count, dtype: int64

In [ ]:
null_attachments['status'].value_counts()

status
processed    2568
Name: count, dtype: int64

In [ ]:
from datetime import datetime, timezone
def get_created_at_from_export_key(export_key: str) -> datetime:
    """Extracts the created_at timestamp from the export data S3 key.

    Args:
        export_key (str): The S3 key of the export data JSON file.
    Returns:
        datetime: The created_at timestamp extracted from the S3 key.
    """
    try:
        parts = export_key.split('/')
        date_part = parts[-3]  # YYYY_MM_DD
        time_part = parts[-2]  # HHMM

        year, month, day = map(int, date_part.split('_'))
        hour = int(time_part[:2])
        minute = int(time_part[2:])

        created_at = datetime(year, month, day, hour, minute, tzinfo=timezone.utc)
        return created_at

    except Exception as e:
        raise ValueError(f"Invalid export key format: {export_key}. Error: {e}")

In [ ]:
def get_export_key_from_created_at(created_at: datetime, filename: str = "export_data.json") -> str:
    """Constructs an S3 export key from a created_at timestamp.

    Args:
        created_at (datetime): The timestamp to convert to an S3 key.
        base_path (str): The base path for the S3 key. Defaults to "export-data".
        filename (str): The filename to use. Defaults to "data.json".
    
    Returns:
        str: The S3 key in format: base_path/YYYY_MM_DD/HHMM/filename
    """
    prefix_source = "ocr-v3/egvp"
    
    date_part = created_at.strftime("%Y_%m_%d")
    time_part = created_at.strftime("%H%M")
    
    export_key = f"{prefix_source}/{date_part}/{time_part}/{filename}"
    return export_key

get one example ticket

In [ ]:
null_attachments

,ticket_uuid,egvp_id,origin,status,attachment_id,created_at
4535,010070b4-2645-4f40-97b3-30a4bdc3ba33,NRW_B2176537402193022953855-a68a-46b2-b4d8-96a...,DE,processed,None,2025-12-10 14:44:00
4537,04701991-8fbc-4966-addd-e63a62b47801,NRW_B21765373964468c9c69973-ae58-4073-8c1b-148...,DE,processed,None,2025-12-10 14:44:00
4538,0795bb8c-719a-4ed4-8bc2-f2f38ace74c4,NRW_B217653724972861892c2bc-59d6-4617-90bc-22f...,DE,processed,None,2025-12-10 14:44:00
4539,1b4046b6-847a-493f-aae2-d1fb1e5d321b,NRW_B21765372888413bdf93a77-3f42-418e-9b3b-59f...,DE,processed,None,2025-12-10 14:44:00
4540,1cec6f5c-d92f-4517-b0a8-9dba83d37214,NRW_B21765374681177011fb821-4496-4e72-9a91-615...,DE,processed,None,2025-12-10 14:44:00
...,...,...,...,...,...,...
18729,aaea6671-9bb7-4482-ab57-38d76d2eaa1c,NRW_B21769445128847fd5148c7-aff6-407c-b01f-bb8...,DE,processed,None,2026-01-26 17:44:00
18730,b0a997d5-36f4-4d99-a2f6-02e49428ee62,NRW_B217694453256116f766068-5118-455a-8ad5-343...,DE,processed,None,2026-01-26 17:44:00
18731,b312b00d-3df5-4507-96d0-1feb254c03f1,NRW_B21769445767818c58f19a5-bf33-491a-8e5e-1ea...,DE,processed,None,2026-01-26 17:44:00
18732,cca364ee-646a-478e-8281-13bfaf38c951,NRW_B21769446134252db39a9b6-1c65-484f-a7a0-381...,DE,processed,None,2026-01-26 17:44:00
18733,fb8852c2-3030-4882-add2-2ee99218b953,NRW_B217694451093154d94315b-9067-4a44-b1f6-0d8...,DE,processed,None,2026-01-26 17:44:00

In [ ]:
index = -1
created_at = null_attachments.iloc[index]['created_at']
ticket_uuid = null_attachments.iloc[index]['ticket_uuid']
egvp_id = null_attachments.iloc[index]['egvp_id']

# Print with colors
print(f"\033[94mIndex:\033[0m \033[92m{index}\033[0m")
print(f"\033[94mCreated At:\033[0m \033[92m{created_at}\033[0m")
print(f"\033[94mTicket UUID:\033[0m \033[92m{ticket_uuid}\033[0m")
print(f"\033[94mEGVP ID:\033[0m \033[92m{egvp_id}\033[0m")

Index: -1
Created At: 2026-01-26 17:44:00
Ticket UUID: fb8852c2-3030-4882-add2-2ee99218b953
EGVP ID: NRW_B217694451093154d94315b-9067-4a44-b1f6-0d8b1459512b

In [ ]:
# read json file from s3
import boto3
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')
bucket_name = "pair-scanner"
export_key = get_export_key_from_created_at(created_at)


print("Getting export data for ticket with created at", created_at, "with key:", export_key)

response = s3.get_object(Bucket=bucket_name, Key=export_key)
content = response['Body'].read().decode('utf-8')
export_data = json.loads(content)

INFO [2026-01-27 10:41:29] - Found credentials in shared credentials file: ~/.aws/credentials

Getting export data for ticket with created at 2026-01-26 17:44:00 with key: ocr-v3/egvp/2026_01_26/1744/export_data.json

In [ ]:
all_egvp_ids = [i['messageId'] for i in export_data]

In [ ]:
egvp_id in all_egvp_ids # this is true, meaning getting the export data worked

True

In [ ]:
null_egvp_data_exported_data = [i for i in export_data if i['messageId'] == egvp_id][0]
null_egvp_data_exported_data

{'id': 297387,
 'messageId': 'NRW_B217694451093154d94315b-9067-4a44-b1f6-0d8b1459512b',
 'attachments': [{'id': 50781739,
   'url': 'https://pair-app-paperclip-production-private.s3.eu-central-1.amazonaws.com/progov_messages/50781739/6_dr_15_26_aus_schreibmaschine.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAICDY7OW4MUGQDC6Q%2F20260126%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260126T174427Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=5bdfeae79d164427cf1f6661501d91038bb088501a172df11e9a4e66af475721'}]}

In [ ]:
null_egvp_data_exported_data['attachments']

[{'id': 50781739,
  'url': 'https://pair-app-paperclip-production-private.s3.eu-central-1.amazonaws.com/progov_messages/50781739/6_dr_15_26_aus_schreibmaschine.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAICDY7OW4MUGQDC6Q%2F20260126%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260126T174427Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=5bdfeae79d164427cf1f6661501d91038bb088501a172df11e9a4e66af475721'}]

Note for this data:
Export key for it look normal. It have attachments. For that message_id (actually egvp_id), there is a record in llm_tickets. But with record's ticket_uuid,
we cannot find any attachment in llm_attachments.
I get the attachment_id of the correspondung egvp data from export key, and search for it in llm_attachments. We have data for it in llm_attachments, textract_jobs and llm_attachment_predictions. But when I get the ticket_uuid of this record coming from llm_attachments, i cannot find any data in llm_tickets.

Meaning that ticket_uuid is changed somehow.
We have records in textract jobs and llm_attachments_predictions too, this means that actually this data first imported normally, passes the pipeline and results are saved. Then ticket_uuid data in the llm_tickets is changed somehow. I need to figure out why the ticket_uuid field is changed

## 📅 Time Tracking Analysis

### Ticket Timeline
| Event | Timestamp | Duration |
|-------|-----------|----------|
| ✅ Ticket created | `2026-01-06 15:44:00` | - |
| 📊 Ticket status written | `2026-01-07 06:11:16` | +14h 27m |

### Attachment Timeline (ID: `48867881`)
| Event | Timestamp | Duration from Ticket Creation |
|-------|-----------|-------------------------------|
| 📎 Attachment created | `2026-01-06 15:44:00` | 0h (simultaneous) |
| 🔍 Attachment's predictions saved | `2026-01-06 22:55:16` | +7h 11m |
| 📝 Attachment status written | `2026-01-06 22:57:41` | +7h 13m |

---

meaning that in llm app this ticket's attachment could be able to found. Meaning probably ticket uuid is not changed in attachment pipeline.

1) It might be changed in llm_queue population (check)
2) Check control flow if it might change the ticket uuid