We have protokol documents very similar to ladung, which model consufes. Get fp examples and re-train the model

In [1]:
import pandas as pd

In [2]:
fp_data = pd.read_csv('/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/data/improvments_data/ladung_fp_protokoll_docs.csv')
latest_full_data = pd.read_csv(r'../data/PFUB_ERLASS_dataset_processed_with_geschaeftsnummer.csv')

In [3]:
fp_data

,attachment_id,s3_link,texts
0,23973761582236-1,s3://pair-data-engineering-new/ocr_prepared_ou...,ANNETTE ZIMMER\nDie nachstehend gewählten Form...
1,24693116189212-1,s3://pair-data-engineering-new/ocr_prepared_ou...,Sven Wiegand\nDie nachstehend gewählten Formul...
2,24823927696284-3,s3://pair-data-engineering-new/ocr_prepared_ou...,JÖRG SCHMIDT\nDie nachstehend gewählten Formul...
3,24824722387996-2,s3://pair-data-engineering-new/ocr_prepared_ou...,Sven Wiegand\nDie nachstehend gewählten Formul...
4,24825525155740-3,s3://pair-data-engineering-new/ocr_prepared_ou...,Sven Wiegand\nDie nachstehend gewählten Formul...
...,...,...,...
214,49736954,s3://pair-data-engineering-new/ocr_prepared_ou...,STEFAN HOFFMANN\nDie nachstehend gewählten For...
215,49747921,s3://pair-data-engineering-new/ocr_prepared_ou...,Manuel Stember\nDie nachstehend gewählten Form...
216,49775489,s3://pair-data-engineering-new/ocr_prepared_ou...,S. Schmitz\nDie nachstehend gewählten Formulie...
217,49778889,s3://pair-data-engineering-new/ocr_prepared_ou...,Frank Lüers\nDie nachstehend gewählten Formuli...
218,49779491,s3://pair-data-engineering-new/ocr_prepared_ou...,Harry Ziegler\nDie nachstehend gewählten Formu...

preprocess fp data

In [4]:
import os

notebook_dir = r'/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks'
project_dir = os.path.dirname(notebook_dir)
print("Notebook Directory:", notebook_dir)
print("Project Directory:", project_dir)
os.chdir(project_dir)

Notebook Directory: /Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks
Project Directory: /Users/melih.gorgulu/Desktop/Projects/intent_recognition

In [5]:
from src.services.attachment_processing.base_input_processor import AfterCourtAttachmentPreprocessor
from src.domain.base.blueprints import AfterCourtPreprocessingBlueprint

In [6]:
# Initialize preprocessor
config = AfterCourtPreprocessingBlueprint(
    normalize_whitespace=True,
    remove_short_lines=True,
    short_line_threshold=3,
    remove_html_tags=True,
    lowercase=True,
    clean_text_type='processed'
)

preprocessor = AfterCourtAttachmentPreprocessor(name='after_court', preprocessing_config=config)

# Apply replace_with_tags directly to each text

fp_data['text_w_tags'] = fp_data['texts'].apply(lambda x: preprocessor._replace_with_tags(preprocessor._process(x)))

In [7]:
fp_data

,attachment_id,s3_link,texts,text_w_tags
0,23973761582236-1,s3://pair-data-engineering-new/ocr_prepared_ou...,ANNETTE ZIMMER\nDie nachstehend gewählten Form...,annette zimmer\ndie nachstehend gewählten form...
1,24693116189212-1,s3://pair-data-engineering-new/ocr_prepared_ou...,Sven Wiegand\nDie nachstehend gewählten Formul...,sven wiegand\ndie nachstehend gewählten formul...
2,24823927696284-3,s3://pair-data-engineering-new/ocr_prepared_ou...,JÖRG SCHMIDT\nDie nachstehend gewählten Formul...,jörg schmidt\ndie nachstehend gewählten formul...
3,24824722387996-2,s3://pair-data-engineering-new/ocr_prepared_ou...,Sven Wiegand\nDie nachstehend gewählten Formul...,sven wiegand\ndie nachstehend gewählten formul...
4,24825525155740-3,s3://pair-data-engineering-new/ocr_prepared_ou...,Sven Wiegand\nDie nachstehend gewählten Formul...,sven wiegand\ndie nachstehend gewählten formul...
...,...,...,...,...
214,49736954,s3://pair-data-engineering-new/ocr_prepared_ou...,STEFAN HOFFMANN\nDie nachstehend gewählten For...,stefan hoffmann\ndie nachstehend gewählten for...
215,49747921,s3://pair-data-engineering-new/ocr_prepared_ou...,Manuel Stember\nDie nachstehend gewählten Form...,manuel stember\ndie nachstehend gewählten form...
216,49775489,s3://pair-data-engineering-new/ocr_prepared_ou...,S. Schmitz\nDie nachstehend gewählten Formulie...,s. schmitz\ndie nachstehend gewählten formulie...
217,49778889,s3://pair-data-engineering-new/ocr_prepared_ou...,Frank Lüers\nDie nachstehend gewählten Formuli...,frank lüers\ndie nachstehend gewählten formuli...
218,49779491,s3://pair-data-engineering-new/ocr_prepared_ou...,Harry Ziegler\nDie nachstehend gewählten Formu...,harry ziegler\ndie nachstehend gewählten formu...

In [8]:
fp_data['document_type'] = 'fp_protocol'
fp_data['is_ladung'] = 0

In [9]:
latest_full_data

,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,tokenized,text_w_tags
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",<PHONE> <NUMBER>\nantrag auf erlass eines pfän...
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,"['antrag', 'erlass', 'pfänd', 'überweisungsbes...",antrag auf erlass eines pfänd <NUMBER><PHONE>\...
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,"['antrag', 'erlass', 'pfändun', 'überweisungsb...",antrag auf erlass eines pfändun\n<PHONE> <NUMB...
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",antrag auf erlass eines pfändungs\n<NUMBER> <N...
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,"['antrag', 'erlass', 'pfändu', 'überweisungsbe...",antrag auf erlass eines pfändu\n<PHONE> <NUMBE...
...,...,...,...,...,...,...,...,...,...
5026,Grover\nFriedhelm August Steiner\nBestellnumme...,NaN,mail_attachments,grover\nfriedhelm august steiner\nbestellnumme...,NaN,False,False,"['grover', 'friedhelm', 'august', 'steiner', '...",grover\nfriedhelm august steiner\nbestellnumme...
5027,Liste des créances\nCréé le: 21.08.2025\nNumér...,NaN,mail_attachments,liste des créances\ncréé le: 21.08.2025\nnumér...,NaN,False,False,"['liste', 'créance', 'créé', 'le', 'numéro', '...",liste des créances\ncréé le: <DATE>\nnuméro de...
5028,11:06\nRetour Détails de la transaction\nPDF\n...,NaN,mail_attachments,"11:06\nretour détails de la transaction\n-209,...",NaN,False,False,"['retour', 'détails', '--', '--', 'transaction...",<NUMBER>:<NUMBER>\nretour détails de la transa...
5029,e\nKLINIKUM\nKlinik für Dermatologie\nNÜRNBERG...,NaN,mail_attachments,klinikum\nklinik für dermatologie\nnürnberg\nu...,NaN,False,False,"['klinikum', 'klinik', 'dermatologie', 'nürnbe...",klinikum\nklinik für dermatologie\nnürnberg\nu...
5030,CP\nDELGMANN + PARTNER\nRECHTSANWÄLTE FACHANWÄ...,NaN,mail_attachments,delgmann + partner\nrechtsanwälte fachanwälte\...,NaN,False,False,"['delgmann', '+', 'partner', 'rechtsanwälte', ...",delgmann + partner\nrechtsanwälte fachanwälte\...

In [10]:
data = pd.concat([latest_full_data, fp_data])[['text_w_tags','document_type','is_ladung']]
data.reset_index(inplace=True,drop=True)

In [11]:
data

,text_w_tags,document_type,is_ladung
0,<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,attachment_and_transfer_order,0
1,antrag auf erlass eines pfänd <NUMBER><PHONE>\...,attachment_and_transfer_order,0
2,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,attachment_and_transfer_order,0
3,antrag auf erlass eines pfändungs\n<NUMBER> <N...,attachment_and_transfer_order,0
4,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,attachment_and_transfer_order,0
...,...,...,...
5245,stefan hoffmann\ndie nachstehend gewählten for...,fp_protocol,0
5246,manuel stember\ndie nachstehend gewählten form...,fp_protocol,0
5247,s. schmitz\ndie nachstehend gewählten formulie...,fp_protocol,0
5248,frank lüers\ndie nachstehend gewählten formuli...,fp_protocol,0
5249,harry ziegler\ndie nachstehend gewählten formu...,fp_protocol,0

In [12]:
data['document_type'].value_counts()

document_type
ladung_va                                 2101
mail_attachments                          1006
monierung_mb                               545
attachment_and_transfer_order              539
approved_seizure                           408
court_inbox                                346
fp_protocol                                219
approved_attachment_and_transfer_order      60
enforcement_order                           23
contradiction                                3
Name: count, dtype: int64

get the vectorizer

In [13]:
import dill
from sklearn.feature_extraction.text import TfidfVectorizer
# Make sure to import ClassificationSpacyLemmaTokenizer from the source code.
from src.services.models.aftercourt_tokenizer import ClassificationSpacyLemmaTokenizer

vec_path = "/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/models/vectorizers/05-12-2026_tf_idf_vectorizer_v1.dill"
tf_idf_vectorizer = dill.load(open(vec_path, 'rb'))

train test split

In [14]:

X_text = data['text_w_tags']
y = data['is_ladung']

# train test split
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train set size: {len(X_train_text)}, Test set size: {len(X_test_text)}")
print(f"Train set is pfub dist: {y_train.value_counts(normalize=True)}")
print(f"Test set is pfub dist: {y_test.value_counts(normalize=True)}")

Train set size: 4200, Test set size: 1050
Train set is pfub dist: is_ladung
0    0.599762
1    0.400238
Name: proportion, dtype: float64
Test set is pfub dist: is_ladung
0    0.6
1    0.4
Name: proportion, dtype: float64

In [15]:
document_types_train = data.loc[X_train_text.index, 'document_type']
document_types_test = data.loc[X_test_text.index, 'document_type']

In [16]:
document_types_train.value_counts()

document_type
ladung_va                                 1681
mail_attachments                           819
monierung_mb                               446
attachment_and_transfer_order              441
approved_seizure                           315
court_inbox                                267
fp_protocol                                164
approved_attachment_and_transfer_order      46
enforcement_order                           18
contradiction                                3
Name: count, dtype: int64

In [17]:
document_types_test.value_counts()

document_type
ladung_va                                 420
mail_attachments                          187
monierung_mb                               99
attachment_and_transfer_order              98
approved_seizure                           93
court_inbox                                79
fp_protocol                                55
approved_attachment_and_transfer_order     14
enforcement_order                           5
Name: count, dtype: int64

In [18]:
X_train_tfidf = tf_idf_vectorizer.transform(X_train_text)
X_test_tfidf = tf_idf_vectorizer.transform(X_test_text)

In [19]:
# basic RF

from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_tfidf, y_train)
y_pred = rf_classifier.predict(X_test_tfidf)

In [20]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)


print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""
    true negatives is :math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, 
    true positives is :math:`C_{1,1}` and false positives is :math:`C_{0,1}
"""

Accuracy: 1.0000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       630
           1       1.00      1.00      1.00       420

    accuracy                           1.00      1050
   macro avg       1.00      1.00      1.00      1050
weighted avg       1.00      1.00      1.00      1050


Confusion Matrix:
[[630   0]
 [  0 420]]

'\n    true negatives is :math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, \n    true positives is :math:`C_{1,1}` and false positives is :math:`C_{0,1}\n'

In [21]:
import pandas as pd

# Create dataframe with predictions, actual values, and original indexes
results_df = pd.DataFrame({
    'index': y_test.index,
    'y_test': y_test.values,
    'y_pred': y_pred
})

results_df

      index  y_test  y_pred
0      3796       0       0
1      2931       1       1
2      4551       0       0
3      2282       0       0
4      1219       1       1
...     ...     ...     ...
1045   1857       1       1
1046   4718       0       0
1047   1106       1       1
1048   1591       0       0
1049   1725       1       1

[1050 rows x 3 columns]

In [22]:
results_df['FP'] = (results_df['y_test'] == 0) & (results_df['y_pred'] == 1)
results_df['FN'] = (results_df['y_test'] == 1) & (results_df['y_pred'] == 0)

In [23]:
results_df

      index  y_test  y_pred     FP     FN
0      3796       0       0  False  False
1      2931       1       1  False  False
2      4551       0       0  False  False
3      2282       0       0  False  False
4      1219       1       1  False  False
...     ...     ...     ...    ...    ...
1045   1857       1       1  False  False
1046   4718       0       0  False  False
1047   1106       1       1  False  False
1048   1591       0       0  False  False
1049   1725       1       1  False  False

[1050 rows x 5 columns]

save the new ladung binary model

In [24]:
# save the trained model
save_path = os.path.join(notebook_dir, "after-court/models/classification/15-01-2026_binary_ladung_rf_classifier_v1.dill")
with open(save_path, "wb") as f:
    dill.dump(rf_classifier, f)