In [1]:
page_count_3_longer = [65437803,
 65443296,
 65444502,
 65446977,
 65414597,
 65444351,
 65442389,
 65409467,
 65394868,
 65445361,
 65402588,
 65402832,
 65444650,
 65436610,
 65402663,
 65445428,
 65442642,
 65402276,
 65445358,
 65409520]

page_count_3_shorter = [65413648,
 65436396,
 65409342,
 65436666,
 65444590,
 65412132,
 65443356,
 65415266,
 65444397,
 65411254,
 65411333,
 65412174,
 65443408,
 65443323,
 65439602,
 65406950,
 65412149,
 65444415,
 65444566,
 65442385]

wrong_pred_my_model = ["65412088"]

page_count_3_shorter = list(map(lambda x:str(x), page_count_3_shorter))
page_count_3_longer = list(map(lambda x:str(x), page_count_3_longer))

In [3]:
# get predictions and documents.
import sys

sys.path.append('../../')
from utils.prod_utils import get_data_by_attachment_id

from python_utilities.db_connection import DbConnection
import boto3
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
# Create session with specific profile
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')

INFO [2026-06-01 15:32:17] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2026-06-01 15:32:17] - Found credentials in shared credentials file: ~/.aws/credentials

In [5]:
# check page_count_3_shorter
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp"
for attachment_id in page_count_3_longer:
    data = get_data_by_attachment_id(attachment_id, analytics_db, s3, pdf_download=True, pdf_download_dir=download_dir)

====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65437803
File Name:       65437803_0_Sammel1.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_377568/65437803_0_Sammel1.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/f9d371f7124b386e8cb41b79b6acd56b820c3c12b564f697a6ee83f5c4f66559.json
│
│ 📊 Text Length:  5595 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65437803.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.06'
│    Prob Pfub:                '0.01'
│    Prob Vermogenverzeichnis: '0.01'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65443296
File Name:       65443296_Dokumente_68326_27052026_124558.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_377834/65443296_Dokumente_68326_27052026_124558.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/ed374419478c12a96c2b6bac618f7e026e7e8961407bff7b7ba23ec3d59dfc82.json
│
│ 📊 Text Length:  4658 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65443296.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.18'
│    Prob Pfub:                '0.04'
│    Prob Vermogenverzeichnis: '0.01'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65444502
File Name:       65444502_2_DR_186_26_08a_An_Gl_Mitt_Ergebnis_Drittauskunft__nur_BZSt.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_377933/65444502_2_DR_186_26_08a_An_Gl_Mitt_Ergebnis_Drittauskunft__nur_BZSt.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/aeba8cec7e42e35ec2d2c65528a94bad80bc5f5f2cb5c86f047835488389e638.json
│
│ 📊 Text Length:  4766 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65444502.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.1'
│    Prob Pfub:                '0.03'
│    Prob Vermogenverzeichnis: '0.005'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65446977
File Name:       65446977_Dokumente_97726_27052026_155954_signed.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_378054/65446977_Dokumente_97726_27052026_155954_signed.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/8f44b2119f26062a9c1f1510af8c75daddf7c23ae2056d37375ce22099eddb14.json
│
│ 📊 Text Length:  9897 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65446977.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.0'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: '0.015'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65414597
File Name:       65414597_DR_II_639_26_An_Gl_Nachricht_HBAntrag.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-26/egvp_id_377372/65414597_DR_II_639_26_An_Gl_Nachricht_HBAntrag.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/d3314837749bd1b59e04e3435cc2c08f7c62ce142253dec299880caefa03a4cf.json
│
│ 📊 Text Length:  7288 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65414597.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.12'
│    Prob Pfub:                '0.01'
│    Prob Vermogenverzeichnis: '0.06'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65444351
File Name:       65444351_12_DR_II_848_26_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_377893/65444351_12_DR_II_848_26_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/e526b67f84032b3ad18d3db9ef20ae262fd7b4e5c3cbac10f71af4338d0572dd.json
│
│ 📊 Text Length:  4784 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65444351.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.07'
│    Prob Pfub:                '0.02'
│    Prob Vermogenverzeichnis: '0.03'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65442389
File Name:       65442389_0_Sammel1.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_377744/65442389_0_Sammel1.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/69f25397808a876214712e4dec44ac8f66533aa5327e22b76900bd897f631e30.json
│
│ 📊 Text Length:  9907 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65442389.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.02'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: '0.045'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65409467
File Name:       65409467_DR_II_321_26_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-26/egvp_id_377146/65409467_DR_II_321_26_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/585891a4b8ebaeefbb6d27b9fc0439eaed7cd2e6bd89f1e9a0d163f1f11ceb27.json
│
│ 📊 Text Length:  6686 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65409467.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.02'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: '0.015'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65394868
File Name:       65394868_DR_II_616_26_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-26/egvp_id_376675/65394868_DR_II_616_26_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/71698518f0219b969d8a84a2b7a3718da79cf7ffc68ad5549cfee9101f844a24.json
│
│ 📊 Text Length:  6317 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65394868.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.02'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: '0.01'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65445361
File Name:       65445361_4_DR_511_26_An_Gl_Nachricht_HBAntrag.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_377987/65445361_4_DR_511_26_An_Gl_Nachricht_HBAntrag.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/d94c9d16628acb5ec4f2cbd9e78b8dad72d9167064329926ca6b39c981e452f2.json
│
│ 📊 Text Length:  5847 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65445361.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.11'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: '0.055'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65402588
File Name:       65402588_Dokumente_56926_26052026_105930-signed.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-26/egvp_id_376949/65402588_Dokumente_56926_26052026_105930-signed.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/facb5c25a88bddf85cda0f9b9e09ff01e857ef7108b35d617854a749108d40e8.json
│
│ 📊 Text Length:  7747 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65402588.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.09'
│    Prob Pfub:                '0.06'
│    Prob Vermogenverzeichnis: '0.02'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65402832
File Name:       65402832_Dokumente_38126_26052026_095957.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-26/egvp_id_376994/65402832_Dokumente_38126_26052026_095957.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/323b8f55dc463c35639924dc162302e063c67bc64fc7aac3e093cbfa80446678.json
│
│ 📊 Text Length:  4675 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65402832.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.18'
│    Prob Pfub:                '0.05'
│    Prob Vermogenverzeichnis: '0.015'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65444650
File Name:       65444650_50_DR_498_26_07b_An_Gl_nicht_erschienen_HB__Drittstellenausk%C3%BCnfte.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_377967/65444650_50_DR_498_26_07b_An_Gl_nicht_erschienen_HB__Drittstellenausk%C3%BCnfte.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/7f26936e0e5b537f4a891f77d9ec08ec1cf681fae2e8da9f93829d6c5bc212f4.json
│
│ 📊 Text Length:  4348 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65444650.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.13'
│    Prob Pfub:                '0.01'
│    Prob Vermogenverzeichnis: '0.03'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65436610
File Name:       65436610_DR_II_410_26_An_Gl_Nachricht_HBAntrag.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-27/egvp_id_377536/65436610_DR_II_410_26_An_Gl_Nachricht_HBAntrag.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/7044a7f38ad7c8812a88ce62b91b2a804e61b54048b14b72c12a48d61d27c020.json
│
│ 📊 Text Length:  9385 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65436610.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.0'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: '0.03'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65402663
File Name:       65402663_DR_II_773_25_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-26/egvp_id_376965/65402663_DR_II_773_25_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/2fd2847c9c57759b8aad26f0feaa71edd66ad0b9c11519050de854d2f3e163b6.json
│
│ 📊 Text Length:  8909 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65402663.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.0'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: '0.005'
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'

In [6]:
data

,attachment_id,document_s3_key,document_s3_bucket,file_name,model_name,type,subtype,value,textract_job_id,textract_status,textract_s3_link,text
0,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_ladung,aftercourt_classification_ladung,aftercourt_type,'ladung_va',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
1,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_ladung,aftercourt_classification_ladung,class_pred,'False',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
2,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_ladung,aftercourt_classification_ladung,class_prob,'0.03',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
3,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_pfub,aftercourt_classification_pfub,aftercourt_type,'pfub_erlass',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
4,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_pfub,aftercourt_classification_pfub,class_pred,'False',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
5,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_pfub,aftercourt_classification_pfub,class_prob,'0.02',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
6,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,aftercourt_type,'vermogenverzeichnis',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
7,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,class_pred,'False',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
8,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,class_prob,'0.015',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
9,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,end_page,'-1',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
10,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,is_invoice_inside,'False',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
11,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,start_page,'-1',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
12,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,invoice_detection_egvp,invoice_detection_egvp,end_page,'-1',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
13,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,invoice_detection_egvp,invoice_detection_egvp,is_invoice_inside,'False',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
14,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,invoice_detection_egvp,invoice_detection_egvp,start_page,'-1',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
15,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,pfub_erlass_egvp,pfub_erlass_egvp,is_invoice_inside,'False',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...
16,65409520,ocr_source_files/2026-05-26/egvp_id_377158/654...,pair-data-engineering-new,65409520_DR_II_267_26_An_Gl_Mitt_Ergebnis_Drit...,pfub_erlass_egvp,pfub_erlass_egvp,is_pfub,'False',2dc8f87e4ef2217dd82eac1adb074305fa77a4fbd74b6d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nJohannes Sell\nAmtsger...

In [7]:

get_data_by_attachment_id('65412088', analytics_db, s3, pdf_download=True, pdf_download_dir=download_dir)

====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   65412088
File Name:       65412088_Lastschrift_01542763E_9a86fb50-24b3-46fa-8c62-0c5e6fdcc8dcE.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-05-26/egvp_id_377255/65412088_Lastschrift_01542763E_9a86fb50-24b3-46fa-8c62-0c5e6fdcc8dcE.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99701599761bfb7bffd7.json
│
│ 📊 Text Length:  3911 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/65412088.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.0'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: '0.03'
│    — invoice_detection_egvp —
│    Start Page:        '1'
│    End Page:          '2'
│    Is Invoice Inside: 'True'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────

,attachment_id,document_s3_key,document_s3_bucket,file_name,model_name,type,subtype,value,textract_job_id,textract_status,textract_s3_link,text
0,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_ladung,aftercourt_classification_ladung,aftercourt_type,'ladung_va',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
1,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_ladung,aftercourt_classification_ladung,class_pred,'False',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
2,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_ladung,aftercourt_classification_ladung,class_prob,'0.0',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
3,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_pfub,aftercourt_classification_pfub,aftercourt_type,'pfub_erlass',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
4,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_pfub,aftercourt_classification_pfub,class_pred,'False',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
5,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_pfub,aftercourt_classification_pfub,class_prob,'0.0',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
6,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,aftercourt_type,'vermogenverzeichnis',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
7,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,class_pred,'False',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
8,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,class_prob,'0.03',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
9,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,end_page,'2',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
10,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,is_invoice_inside,'True',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
11,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,aftercourt_classification_vermogenverzeichnis,aftercourt_classification_vermogenverzeichnis,start_page,'1',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
12,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,invoice_detection_egvp,invoice_detection_egvp,end_page,'2',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
13,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,invoice_detection_egvp,invoice_detection_egvp,is_invoice_inside,'True',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
14,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,invoice_detection_egvp,invoice_detection_egvp,start_page,'1',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
15,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,pfub_erlass_egvp,pfub_erlass_egvp,is_invoice_inside,'True',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...
16,65412088,ocr_source_files/2026-05-26/egvp_id_377255/654...,pair-data-engineering-new,65412088_Lastschrift_01542763E_9a86fb50-24b3-4...,pfub_erlass_egvp,pfub_erlass_egvp,is_pfub,'False',1f86f1187c7f6b785a09d52a05fc7277e4cb1d46338c99...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Stuttgart\nBlatt\n1\nGeschäftsnumm...

In [14]:
# fetch attachment ids

def get_llm_reasoning_by_attachment_id(attachment_ids, analytics_db, graph_db):
    attachment_ids_str = ",".join([f"'{id}'" for id in attachment_ids])
    query = f"""
    SELECT ticket_uuid
    FROM llm_attachments
    WHERE attachment_id IN ({attachment_ids_str})
    """
    ticket_uuids = analytics_db.sql_to_df(query)
    
    query = f"""
    SELECT *
    FROM public.gpu_tasks
    WHERE ticket_uuid IN ({','.join([f"'{uuid}'" for uuid in ticket_uuids['ticket_uuid'].tolist()])})
    """
    gpu_tasks = graph_db.sql_to_df(query)
    return gpu_tasks

In [15]:
graph_db = DbConnection('GRAPH_DB', 'GRAPH_DATABASE_URI')

get_llm_reasoning_by_attachment_id(['65412088','65409520'], analytics_db, graph_db)

INFO [2026-06-01 15:36:28] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

AttributeError: Query execution failed:
    SELECT *
    FROM public.gpu_tasks
    WHERE ticket_uuid IN ('7d5f2026-34d3-56e2-aac5-5b2f2ffb3c50','a177ce59-4399-5663-868d-6dd734a2492e')